name: whorl
favicon: null
layout_spectrum: 0.8538513546809554
typography_spectrum: 0.012315080966800451
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.25350794522091746
  lightness: 0.5049449775833637
  saturation: 0.2073073375504464
  rhythmicContrast: 0.8644419100601226
purpose: []
